---
- name: Install Git package
  yum:
    name: git
    state: present

- name: Add git user.name
  shell: git config --global user.name "Matt Rybin"

- name: Add git user.email
  shell: git config --global user.email "matt@sala.co"

- name: ensure private key and public one are present
  copy:
    src: keys/
    dest: "/home/ec2-user/.ssh"
    mode: 0600
  with_items:
    - git-macbook.pub
    - git-macbook

- name: Change user, group and permissions for authorized_keys
  file:
    path: /home/ec2-user/.ssh/authorized_keys
    owner: ec2-user
    group: ec2-user
    mode: '0644'

- name: Change user, group and permissions for private key
  file:
    path: /home/ec2-user/.ssh/git-macbook
    owner: ec2-user
    group: ec2-user
    mode: '0600'


- name: Change user, group and permissions for public key
  file:
    path: /home/ec2-user/.ssh/git-macbook.pub
    owner: ec2-user
    group: ec2-user
    mode: '0644'

- name: Add public key to authorized_keys
  shell: cat /home/ec2-user/.ssh/git-macbook.pub >> /home/ec2-user/.ssh/authorized_keys

- name: Add private key to /etc/ssh/ssh_config
  shell: echo -e "IdentityFile ~/.ssh/git-macbook" | tee -a /etc/ssh/ssh_config